version: '3.8'

services:
  jahkon_collections_app:
    image: node:24-alpine
    container_name: jahkon_collections_app
    restart: unless-stopped
    working_dir: /app
    command: sh -c "node .svelte-kit/output/server/index.js"
    volumes:
      - .:/app
    ports:
      - "5173:3000"
      - "5173:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    # depends_on:
    #   - db
    #   - meilisearch
    networks:
      - jahkon-net

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jahkon-net

  meilisearch:
    image: getmeili/meilisearch:v1.8
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    # ports:
    #   - "7700:7700"
    volumes:
      - meili_data:/meili_data
    networks:
      - jahkon-net

volumes:
  postgres_data:
  meili_data:

networks:
  jahkon-net:
    driver: bridge
